# Generated by Django 3.0.3 on 2020-03-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_bed_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bed',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
