# Generated by Django 3.0.3 on 2020-03-03 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200303_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('surgery-or-abdomen', 'Дотор / Мэс засал'), ('maternity', 'Эх барих'), ('premature', 'Хүүхэд'), ('other', 'Бусад')], max_length=20)),
                ('current', models.PositiveIntegerField()),
                ('increment', models.PositiveIntegerField()),
                ('decrement', models.PositiveIntegerField()),
                ('final', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Project')),
            ],
        ),
    ]
