# Generated by Django 2.0 on 2020-03-04 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_bed_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todo.Projects'),
        ),
        migrations.AlterModelTable(
            name='servicetype',
            table='service',
        ),
    ]
