# Generated by Django 2.0 on 2020-03-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200304_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dreamreal',
            name='online',
        ),
        migrations.DeleteModel(
            name='Dreamreal',
        ),
        migrations.DeleteModel(
            name='Online',
        ),
    ]
