# Generated by Django 2.1.5 on 2020-03-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20200304_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Projects'),
        ),
    ]
