# Generated by Django 2.1.5 on 2020-03-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20200304_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='project',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
